- hosts: all
  become: true
  tasks:
    - name: Install Docker and Docker Compose dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lxcfs
          - python-pip
        state: present

    - name: Add Docker repository
      yum_repository:
        name: docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
        gpgcheck: yes
        state: present

    - name: Install Docker Engine
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Option A: Use pre-configured Docker image (recommended) - Skip following steps
    # Option B: Install Docker Compose with pip (if not using pre-configured image)
    - name: Install docker python library (for Docker Compose with pip)
      when: not ansible_virtualization_role == "guest"  # Skip if using containerized Ansible

      pip:
        name: docker
        state: present

    - name: Install Docker Compose with pip (for pip option)
      when: not ansible_virtualization_role == "guest"  # Skip if using containerized Ansible

      pip:
        name: docker-compose
        state: present

    - name: Check Docker version
      command: docker version
      register: docker_version
    - debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check Docker Compose version
      command: docker-compose version
      register: docker_compose_version
    - debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"